// Reads web/dist and emits server/assets.generated.ts — a base64 map of the
// built frontend. `bun build --compile` then bakes that module into the binary,
// so `helm` is a single self-contained file that needs no web/dist on disk.
// The generated file is gitignored; it is produced fresh on every build.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { extname, join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const distDir = join(root, "web/dist");
const outFile = join(root, "server/assets.generated.ts");

const TYPES: Record<string, string> = {
  ".html": "text/html;charset=utf-8",
  ".js": "text/javascript;charset=utf-8",
  ".mjs": "text/javascript;charset=utf-8",
  ".css": "text/css;charset=utf-8",
  ".json": "application/json;charset=utf-8",
  ".map": "application/json;charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain;charset=utf-8",
};

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

let files: string[] = [];
try {
  files = await walk(distDir);
} catch {
  console.error(`embed: ${distDir} not found — run the web build first.`);
  process.exit(1);
}

const map: Record<string, { b64: string; type: string }> = {};
for (const f of files) {
  const urlPath = "/" + relative(distDir, f).split(/[\\/]/).join("/");
  const bytes = await readFile(f);
  const type = TYPES[extname(f).toLowerCase()] ?? "application/octet-stream";
  map[urlPath] = { b64: bytes.toString("base64"), type };
}

const banner = "// AUTO-GENERATED by scripts/embed.ts — do not edit. Embeds web/dist into the binary.\n";
const body = `export const ASSETS: Record<string, { b64: string; type: string }> = ${JSON.stringify(map)};\n`;
await writeFile(outFile, banner + body, "utf8");

const kb = Math.round((banner.length + body.length) / 1024);
console.log(`embed: ${Object.keys(map).length} assets -> server/assets.generated.ts (${kb} KB)`);
